server:
  port: 8003
hiu:
  id: 10000002
  name: Max Health Care
  dataPushUrl: http://localhost:8003/data/notification
  valueSets: classpath:/static/ValueSet/ncg-valuesets.json
  disableHttpOptionsMethod: false
  hfrAffinityDomains: facilitysbx.ndhm.gov.in
  consentmanager:
    suffix: '@ncg'
    url: http://localhost:9000
  dataflowservice:
    defaultPageSize: 20
    maxPageSize: 100
    localStoragePath: /tmp/
    #Time in minutes
    dataFlowRequestWaitTime: 1
    dataPartWaitTime: 1
  userservice:
    jwkUrl: http://localhost:9001/auth/realms/consent-manager/protocol/openid-connect/certs
  consentservice:
    consentRequestFromYears: 7
    consentExpiryInMonths: 2
    consentRequestDelay: 2
  authorization:
    header: ${AUTHORIZATION_HEADER:Authorization}
    useCMAsIDP: ${USE_CM_AS_IDP:true}
    externalIdpCertPath: ${IDP_CERT_PATH}   #Used when useCMAsIDP is false
    externalIdpClientId: ${IDP_CLIENT_ID}
    externalIdpClientSecret: ${IDP_SECRET}
    externalIdpAuthURL: ${IDP_AUTH_URL}
  database:
    host: localhost
    port: 5432
    schema: health_information_user
    user: postgres
    password: password
    poolSize: 5
  dataflow:
    offsetInDays: 2
    usingGateway: false
  dicomserver:
    url: http://localhost:8042
    user: orthanc
    password: orthanc
  gatewayservice:
    baseUrl: http://localhost:8000/v0.5
    requestTimeout: 2000
    clientId: 10000002
    clientSecret: ${CLIENT_SECRET}
    jwkUrl: http://localhost:8000/v0.5/certs
keystore:
  file-path: "phiu-local-keystore.p12"
  password: password
  sign-consent-request-keypair:
    store-type: PKCS12
    alias: phiu-sign-cr
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    queuePrefix: ""
  codec:
    max-in-memory-size: 500MB
