name: HIU master build

on:
  push:
    branches:
      - hiu-fork
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build and unit tests
        run: ./gradlew clean build
      - name: Code coverage
        run: ./gradlew jacocoTestReport
      - name: Sonarcube Analysis
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew sonarqube
      - name: Set env
        run: echo ::set-env name=RELEASE_VERSION::$(echo $GITHUB_SHA | head -c7)
      - name: Docker Registry
        env:
          DOCKER_REGISTRY_URL: docker.io
          DOCKER_PASSWORD: ${{ secrets.DOCKER_NHA_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_NHA_USERNAME }}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD $DOCKER_REGISTRY_URL
      - name: Build docker image
        env:
          IMAGE_NAME: nha20/jas-health-information-user
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: docker build -t $IMAGE_NAME:$RELEASE_VERSION -t $IMAGE_NAME:latest .
      - name: Push Docker Container to Registry
        env:
          IMAGE_NAME: nha20/jas-health-information-user
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: docker push $IMAGE_NAME
